/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     | Website:  https://openfoam.org
    \\  /    A nd           | Copyright (C) 2011-2019 OpenFOAM Foundation
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

Class
    Foam::coupledMaxErrorFvPatchScalarField

Description
    Foam::coupledMaxErrorFvPatchScalarField

SourceFiles
    coupledMaxErrorFvPatchScalarField.C

\*---------------------------------------------------------------------------*/

#ifndef coupledMaxErrorFvPatchScalarField_H
#define coupledMaxErrorFvPatchScalarField_H

#include "Random.H"
#include "fixedValueFvPatchFields.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

/*---------------------------------------------------------------------------*\
                     Class coupledCellMotionFvPatchVectorField Declaration
\*---------------------------------------------------------------------------*/

class coupledMaxErrorFvPatchScalarField
:
    public fixedValueFvPatchField<scalar>
{
public:

    //- Runtime type information
    TypeName("coupledMaxError");


    // Constructors

        //- Construct from patch and internal field
        coupledMaxErrorFvPatchScalarField
        (
            const fvPatch&,
            const DimensionedField<scalar, volMesh>&
        );

        //- Construct from patch, internal field and dictionary
        coupledMaxErrorFvPatchScalarField
        (
            const fvPatch&,
            const DimensionedField<scalar, volMesh>&,
            const dictionary&
        );

        //- Construct by mapping given coupledMaxErrorFvPatchScalarField
        //  onto a new patch
        coupledMaxErrorFvPatchScalarField
        (
            const coupledMaxErrorFvPatchScalarField&,
            const fvPatch&,
            const DimensionedField<scalar, volMesh>&,
            const fvPatchFieldMapper&
        );

        //- Copy constructor
        coupledMaxErrorFvPatchScalarField
        (
            const coupledMaxErrorFvPatchScalarField&
        ) = delete;

        //- Copy constructor setting internal field reference
        coupledMaxErrorFvPatchScalarField
        (
            const coupledMaxErrorFvPatchScalarField&,
            const DimensionedField<scalar, volMesh>&
        );

        //- Construct and return a clone setting internal field reference
        virtual tmp<fvPatchField<scalar>> clone
        (
            const DimensionedField<scalar, volMesh>& iF
        ) const
        {
            return tmp<fvPatchField<scalar>>
            (
                new coupledMaxErrorFvPatchScalarField(*this, iF)
            );
        }


    // Member Functions

        //- Update the coefficients associated with the patch field
        virtual void updateCoeffs();

        //- Write
        virtual void write(Ostream&) const;
};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
