#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# -- Create paraview file
paraFoam -builtin -touch

# -- Create mesh
runApplication blockMesh

# -- Decompose the case
runApplication decomposePar

# -- Set initial conditions
runParallel setRefinedFields

# -- run the calc
runParallel $(getApplication)


# ----------------------------------------------------------------- end-of-file
