#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication decomposePar
# runParallel setFields
runParallel setRefinedFields
runParallel $(getApplication)


# ----------------------------------------------------------------- end-of-file
