#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication generateMoments
runApplication decomposePar
runParallel setRefinedFields

# -- run the calc
runParallel $(getApplication)
