#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

(cd src && ./Allwclean)
(cd applications && wclean all)

# ----------------------------------------------------------------- end-of-file
