#!/bin/bash
#
createEps()
{
    echo "creating $1 plot"
    gnuplot<<EOF

    set terminal postscript eps enhanced color font 'Helvetica,40' linewidth 2\
        dl 8.0
    set output "blastFoam_KB_validation_$9.eps"
    set xlabel "Radius [m]"
    set ylabel "$1 [$2]"
    set grid
    set key center top
    set size 2,2
    set autoscale
    set xrange [1:10]
    plot    "$7" using 1:(\$$8) title 'Swisdak (1994)'\
                with points pt 5 ps 2 lc rgb 'blue',\
            "$3" using 1:(\$$5*$6) every 3 title 'blastFoam (x)'\
                with lines lt 1 linewidth 2 lc rgb 'black', \
            "$4" using 1:(\$$5*$6) every 3 title 'blastFoam (y)'\
                with lines dt 2 linewidth 2 lc rgb 'red'

EOF
}

# test if gnuplot exists on the system
if ! which gnuplot > /dev/null 2>&1
then
    echo "gnuplot not found - skipping graph creation" >&2
    exit 1
fi

BLASTFOAM_clx="../postProcessing/sampleDict/*/Centerlinex*"
BLASTFOAM_cly="../postProcessing/sampleDict/*/Centerliney*"
Swisdak="validationData/SwisdakData.csv"


createEps "Maximum Overpressure" "kPa" $BLASTFOAM_clx $BLASTFOAM_cly 2 0.001 $Swisdak 2 "overpressure"
createEps "Maximum Impulse" "kPa ms" $BLASTFOAM_clx $BLASTFOAM_cly 3 1.0 $Swisdak 3 "impulse"
createEps "Time of arrival" "ms" $BLASTFOAM_clx $BLASTFOAM_cly 4 1000 $Swisdak 4 "toa"

echo Done
