#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

foamCleanCase -case axisymmetricCharge
foamCleanCase -case building3D

# ----------------------------------------------------------------- end-of-file
