#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication setFields
runApplication $(getApplication)
runApplication postProcess -func sampleDict -latestTime
runApplication -o postProcess -func sampleDict -time 0.0001
runApplication -o postProcess -func sampleDict -time 5e-5
runApplication -o postProcess -func sampleDict -time 0

(cd validation && ./createGraphs)

# ----------------------------------------------------------------- end-of-file
