#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

paraFoam -builtin -touch

# -- Extract surface features
runApplication surfaceFeatures

#-- Create the base mesh
runApplication blockMesh

# -- Decompose the case
runApplication decomposePar -copyZero

# -- Refine and snap geometry
runParallel snappyHexMesh -overwrite

# -- Refine the window
runParallel addInternalPatch -noFields

# -- Refine the window
runParallel -s windows setRefinedFields -noFields

# -- Select faces to add to the windows
runParallel topoSet

#-- Create windows
runParallel createBaffles -overwrite

runParallel splitBaffles -overwrite

# -- Add internal patch
runParallel -s master addEmptyPatch windowsBurst_master wall -overwrite -noFields
runParallel -s slave addEmptyPatch windowsBurst_slave wall -overwrite -noFields

# -- Create overlapping couple patches for "internal" faces
runParallel createNonConformalCouples windowsBurst_master windowsBurst_slave -overwrite

# -- Set the charge
runParallel setRefinedFields

# -- run the calc
# runParallel $(getApplication)
