#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# set -x

if [ -z "$QBMM_INST_DIR" ]
then
    echo "**************************************************"
    echo "    QBMM_INST_DIR has not been defined."
    echo "    QBMM solvers will not be compiled."
    echo "    Please add \"export QBMM_INST_DIR=QBMM_DIR\""
    echo "    to you .bashrc file, before sourcing blastfoam"
    echo "**************************************************"
elif [ ! -d "$QBMM_INST_DIR" ]
then
    echo "**************************************************"
    echo "    $QBMM_INST_DIR is not a valid directory."
    echo "    QBMM solvers will not be compiled."
    echo "**************************************************"
else
    wmake $targetType blastPbeTransportFoam
    wmake all blastVdfTransportFoam
fi
