#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# set -x

if [ -z "$QBMM_INST_DIR" ]
then
    echo "Please add \"export QBMM_INST_DIR=QBMM_DIR\" to you .bashrc file"
else
    wmake $targetType blastPbeTransportFoam
    wmake all blastVdfTransportFoam
fi
