
#include "idealGasPressureBoundaryTraction.H"
#include "uniformDimensionedFields.H"
#include "polygonTriangulate.H"
#include "SubField.H"
#include "addToRunTimeSelectionTable.H"

// * * * * * * * * * * * * * * Static Data Members * * * * * * * * * * * * * //

namespace Foam
{
namespace boundaryTractions
{
    defineTypeNameAndDebug(idealGasPressure, 0);
    addToRunTimeSelectionTable
    (
        boundaryTraction,
        idealGasPressure,
        dictionary
    );
}
}


Foam::scalar Foam::boundaryTractions::idealGasPressure::calcV
(
    const pointField& points,
    const faceList& faces
)
{
    // Reimplemented from: Wm4PolyhedralMassProperties.cpp
    // File Version: 4.10.0 (2009/11/18)

    // Geometric Tools, LC
    // Copyright (c) 1998-2010
    // Distributed under the Boost Software License, Version 1.0.
    // http://www.boost.org/LICENSE_1_0.txt
    // http://www.geometrictools.com/License/Boost/LICENSE_1_0.txt

    // Boost Software License - Version 1.0 - August 17th, 2003

    // Permission is hereby granted, free of charge, to any person or
    // organisation obtaining a copy of the software and accompanying
    // documentation covered by this license (the "Software") to use,
    // reproduce, display, distribute, execute, and transmit the
    // Software, and to prepare derivative works of the Software, and
    // to permit third-parties to whom the Software is furnished to do
    // so, all subject to the following:

    // The copyright notices in the Software and this entire
    // statement, including the above license grant, this restriction
    // and the following disclaimer, must be included in all copies of
    // the Software, in whole or in part, and all derivative works of
    // the Software, unless such copies or derivative works are solely
    // in the form of machine-executable object code generated by a
    // source language processor.

    // THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
    // EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
    // OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND
    // NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR
    // ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR
    // OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    // ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
    // USE OR OTHER DEALINGS IN THE SOFTWARE.

    scalar V = 0.0;
    polygonTriangulate engine;

    forAll(faces, i)
    {
        const face& f = faces[i];
        if (f.size() == 3)
        {
            // vertices of triangle i
            const vector& v0 = points[f[0]];
            const vector& v1 = points[f[1]];
            const vector& v2 = points[f[2]];

            // cross product of edges
            const vector n((v1 - v0) ^ (v2 - v0));

            // update volume
            V += n.x()*(v0.x() + v1.x() + v2.x());
        }
        else
        {
            const List<triFace>& triFaces = engine.triangulate
            (
                UIndirectList<point>(points, f)
            );
            forAll(triFaces, tfi)
            {
                const triFace& tf = triFaces[tfi];

                // vertices of triangle i
                const vector& v0 = points[tf[0]];
                const vector& v1 = points[tf[1]];
                const vector& v2 = points[tf[2]];

                // cross product of edges
                const vector n((v1 - v0) ^ (v2 - v0));

                // update volume
                V += n.x()*(v0.x() + v1.x() + v2.x());
            }
        }
    }
    return -returnReduce(V, sumOp<scalar>())/6.0;
}


// * * * * * * * * * * * * * * * * Constructors  * * * * * * * * * * * * * * //

Foam::boundaryTractions::idealGasPressure::idealGasPressure
(
    const word& name,
    const dictionary& dict,
    const feMesh1& femesh,
    const pointVectorField* DPtr
)
:
    boundaryTraction(name, dict, femesh, DPtr),
    p0_(dict.lookup<scalar>("p0")),
    VRef_(0.0),
    pRef_(dict.lookupOrDefault("pRef", 0.0)),
    p_(p0_ - pRef_)
{
    uniformDimensionedScalarField* VRefPtr =
        new uniformDimensionedScalarField
        (
            IOobject
            (
                IOobject::groupName("VRef", name),
                mesh_.time().timeName(),
                "uniform",
                mesh_,
                IOobject::READ_IF_PRESENT,
                IOobject::AUTO_WRITE
            ),
            dimensionedScalar("V", dimVolume, 0.0)
        );
    if (!VRefPtr->headerOk())
    {
        // Reference to the poly patch
        const polyPatch& pp = mesh_.boundaryMesh()[patchID_];

        // Ensure the volume is closed
        const vector sumSf(gSum(pp.faceAreas()));
        if (mag(sumSf) > sqrt(small))
        {
            FatalErrorInFunction
                << name << " is not a closed boundary."
                << "residual area: " << sumSf << endl
                << abort(FatalError);
        }

        // Create the tri faces
        tmp<pointField> tpoints;
        if (DPtr_)
        {
            tpoints =
                pp.localPoints()
              + pointField(*DPtr_, pp.meshPoints());
        }
        else
        {
            tpoints = tmp<pointField>(pp.localPoints());
        }

        // Calculate the initial volume
        VRef_ = calcV(tpoints(), pp.localFaces());
        VRefPtr->value() = VRef_;
    }
    VRefPtr->store(VRefPtr);

}


Foam::boundaryTractions::idealGasPressure::idealGasPressure
(
    const idealGasPressure& igpbt
)
:
    boundaryTraction(igpbt),
    p0_(igpbt.p0_),
    VRef_(igpbt.VRef_),
    pRef_(igpbt.pRef_),
    p_(igpbt.p_)
{}


// * * * * * * * * * * * * * * * * Destructor  * * * * * * * * * * * * * * * //

Foam::boundaryTractions::idealGasPressure::~idealGasPressure()
{}


// * * * * * * * * * * * * * * * Member Functions  * * * * * * * * * * * * * //

void Foam::boundaryTractions::idealGasPressure::update()
{
    const polyPatch& pp = mesh_.boundaryMesh()[patchID_];

    // Determine points to use
    tmp<pointField> tpoints;

    // If the displacement field is needed, add displacement to mesh points
    if (DPtr_)
    {
        tpoints =
            pp.localPoints()
          + pointField(*DPtr_, pp.meshPoints());
    }
    else
    {
        tpoints = tmp<pointField>(pp.localPoints());
    }

    // Current volume
    const scalar V = calcV(tpoints(), pp.localFaces());

    // Calculate pressure inside the ball
    p_ = p0_*VRef_/V - pRef_;
}


Foam::scalar Foam::boundaryTractions::idealGasPressure::pressure
(
    const labelList& nodeLabels,
    const scalarList& shape,
    const vector& n
) const
{
    return p_;
}


Foam::vector Foam::boundaryTractions::idealGasPressure::traction
(
    const labelList& nodeLabels,
    const scalarList& shape,
    const vector& n
) const
{
   return Zero;
}


// ************************************************************************* //
