#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

wmake -all $targetType utilities
wmake -all $targetType modules
wmake -all $targetType solvers

# -----------------------------------------------------------------------------

