#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication generateMoments
runApplication setFields
runApplication $(getApplication)

postProcess -func sampleDict -time '0.0001'
postProcess -func sampleDict -time '0.0002'

(cd validation && ./createGraphs)

