#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication setFields
runApplication blastFoam
runApplication postProcess -func sampleDict -latestTime

(cd validation && ./createGraphs)

# ----------------------------------------------------------------- end-of-file
