#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

paraFoam -builtin -touch

runApplication blockMesh -dict system/blockMeshDict_3D

runApplication decomposePar

runParallel $(getApplication)

# ----------------------------------------------------------------- end-of-file
