#!/bin/bash
#
# Results taken from:
#   Luo, H., Baum, J. D., Lohner, R. (2003)
#   "On the computation of multi-material flows using ALE formulation"
#   Journal of Computational Physics, 194, 304-328

createEpsP()
{

    gnuplot<<EOF
    set terminal postscript eps enhanced color font 'Helvetica,40' linewidth 2\
        dl 8.0
    set output "blastFoam_shockTube_validation_p.eps"
    set xlabel "X-Position (m)"
    set ylabel "Pressure [Pa]"
    set grid
    set key right top
    set size 2,2
    set autoscale
    set xrange [0:100]
    plot    "$1" using 1:2 title 'Exact'\
                with points linewidth 8 linecolor rgb 'black',\
            "$2" using 1:2 title 'blastFOAM'\
                with lines lt 1 linewidth 2 linecolor rgb 'black'
EOF
}

createEpsRho()
{

    gnuplot<<EOF
    set terminal postscript eps enhanced color font 'Helvetica,40' linewidth 2\
        dl 8.0
    set output "blastFoam_shockTube_rho.eps"
    set xlabel "X-Position (m)"
    set ylabel "Density [kg/m^3]"
    set grid
    set key right top
    set size 2,2
    set autoscale
    set xrange [0:100]
    plot    "$1" using 1:2 title 'Exact'\
                with points linewidth 8 linecolor rgb 'black',\
            "$2" using 1:3 title 'blastFOAM'\
                with lines lt 1 linewidth 2 linecolor rgb 'black'
EOF
}

createEpsUx()
{

    gnuplot<<EOF
    set terminal postscript eps enhanced color font 'Helvetica,40' linewidth 2\
        dl 8.0
    set output "blastFoam_shockTube_validation_Ux.eps"
    set xlabel "X-Position (m)"
    set ylabel "Velocity [m/s]"
    set grid
    set key left top
    set size 2,2
    set autoscale
    set xrange [0:100]
    plot    "$1" using 1:2 title 'Exact'\
                with points linewidth 8 linecolor rgb 'black',\
            "$2" using 1:2 title 'blastFOAM'\
                with lines lt 1 linewidth 2 linecolor rgb 'black'
EOF
}

# test if gnuplot exists on the system
if ! which gnuplot > /dev/null 2>&1
then
    echo "gnuplot not found - skipping graph creation" >&2
    exit 1
fi

# paths to data
VALIDATIONDATAROOT=./validationData

pVal="$VALIDATIONDATAROOT/p.csv"
rhoVal="$VALIDATIONDATAROOT/density.csv"
uVal="$VALIDATIONDATAROOT/U.csv"
pRhoBlastFOAM="../postProcessing/sampleDict/20/Centerline_p*"
UBlastFOAM="../postProcessing/sampleDict/20/Centerline_U*"

createEpsP $pVal $pRhoBlastFOAM
createEpsRho $rhoVal $pRhoBlastFOAM
createEpsUx $uVal $UBlastFOAM

echo Done
