#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# -- Create paraview file
paraFoam -builtin -touch

# -- Create the mesh for the fluid
runApplication blockMesh

# -- Transform points
runApplication transformPoints -scale "(1 0 1)"

# -- Extrude the mesh
runApplication extrudeMesh

#- Run the calc
runApplication $(getApplication)

#- Conver lagrangian positions
runApplication convertLagrangianPositions

#------------------------------------------------------------------------------
