#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create base mesh
runApplication blockMesh

# Se the charge
runApplication setRefinedFields

#Run calculation
runApplication blastFoam

# ----------------------------------------------------------------- end-of-file
