#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
cleanSamples

rm -rf constant/*/polyMesh 0/cellToRegion 0/*/cellToRegion 0/*/polyMesh 0/*/cellLevel

rm -f validation/*.eps

# ----------------------------------------------------------------- end-of-file
