#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

paraFoam -builtin -touch

runApplication -s air blockMesh -region air
runApplication -s flap blockMesh -region flap

runApplication decomposePar -allRegions

# -- Add internal patch
runParallel addEmptyPatch internalPatch internal -region air -overwrite

runParallel setRefinedFields -region air

runParallel $(getApplication)

# ----------------------------------------------------------------- end-of-file
