#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# -- Create paraview file
paraFoam -builtin -touch

# -- Create the mesh for the air
runApplication -s air blockMesh -region air

# -- Create the mesh for the flap
runApplication -s flap blockMesh -region flap

# -- Decompose the meshes
runApplication decomposePar -allRegions

# -- Set the initial conditions for the air
runParallel setRefinedFields -region air

# -- Run the calc
runParallel $(getApplication)

# ----------------------------------------------------------------- end-of-file
