#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

paraFoam -builtin -touch
runApplication blockMesh
runApplication addTinyPatch free fixed -points "((-1.5 -0.4 0)(1.5 -0.4 0))"
runApplication $(getApplication)
