#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# -- Create paraview file
paraFoam -builtin -touch

# -- Create the mesh for the fluid
runApplication blockMesh

# -- Create outlet patch face set
runApplication -s patch setRefinedFields -noFields -overwrite -noRefine

# -- Create outlet patch
runApplication createPatch -overwrite

# -- Create face zone for the window
runApplication -s windows setRefinedFields -noFields -overwrite -noRefine

# -- Create baffles
runApplication createBaffles -overwrite

# -- Remove zones
runApplication removeZones -allFaces

# -- Split the baffles so faces use different points (necessary for AMR)
runApplication splitBaffles -overwrite

# -- Select cells to remove ("walls")
runApplication -s cells setRefinedFields -noFields -overwrite -noRefine

# -- Remove walls
runApplication subsetMesh -patch walls internalCells -overwrite -noFields

# -- Add burst patches (same as intact but are mapped when overlapping)
runApplication -s burst_master addEmptyPatch windowsBurst_master wall -overwrite
runApplication -s burst_slave addEmptyPatch windowsBurst_slave wall -overwrite

# -- Create overlapping couple patches for "internal" faces
runApplication createNonConformalCouples windowsBurst_master windowsBurst_slave -overwrite -fields

# -- Set the initial conditions for the fluid
runApplication setRefinedFields

# -- Run the calc
runApplication $(getApplication)

# ----------------------------------------------------------------- end-of-file
