#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

paraFoam -builtin -touch

nDims=3
blockMeshDict="blockMeshDict_${nDims}D"

runApplication -s air blockMesh -region air -dict system/air/$blockMeshDict
runApplication -s plate blockMesh -region plate -dict system/plate/$blockMeshDict

runApplication decomposePar -allRegions

runParallel setRefinedFields -region air

runParallel $(getApplication)

# ----------------------------------------------------------------- end-of-file
