#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#-- Remove link
rm axisymmetricCharge

# -- Clean the cases
sector/Allclean
wedge/Allclean
building3D/Allclean

# ----------------------------------------------------------------- end-of-file
