#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


# runApplication gmshToFoam ./gmsh/chamber-coarse.msh
# runApplication changeDictionary
runApplication blockMesh
runApplication setFields
runApplication decomposePar
runParallel $(getApplication)

# ----------------------------------------------------------------- end-of-file
