#----------------------------------*-sh-*--------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | www.synthetik-technologies.com
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
#     Copyright (C) 2020 Synthetik Applied Technologies
#------------------------------------------------------------------------------
# License
#     This file is derivative work of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# File
#     etc/bashrc
#
# Description
#     Startup file for blastFoam
#     Sourced from ~/.profile or ~/.bashrc
#     Should be usable by any POSIX-compliant shell (eg, ksh)
#
#------------------------------------------------------------------------------

# Some compatibility methods (OPENFOAM-v2012 and later or Oct-2020 develop)
export FOAM_EXTRA_CXXFLAGS="-DCOMPAT_OPENFOAM_ORG"

################################################################################
# USER EDITABLE PART: Changes made here may be lost with the next upgrade
#
# BLAST_DIR is the location of the blastfoam installation which defaults to
# the directory containing this file if sourced by a bash shell.
# Set to one directory level higher than the current by default
#
export BLAST_DIR="$( cd ../ && pwd )"

# Export location of libraries and executables
export BLAST_LIBBIN="$FOAM_USER_LIBBIN"
export BLAST_APPBIN="$FOAM_USER_APPBIN"
#export BLAST_LIBBIN="$FOAM_SITE_LIBBIN"
#export BLAST_APPBIN="$FOAM_SITE_APPBIN"

# OpenQBMM install directory (needs to be defined before here)
if [ -n "$QBMM_INST_DIR" ]
then

# Set location of libraries and apps for OpenQBMM
export QBMM_LIBBIN=$FOAM_USER_LIBBIN
export QBMM_APPBIN=$FOAM_USER_APPBIN

# Set OpenQBMM libraries to use in Make files
export QBMM_LIBS="-L\$(QBMM_LIBBIN) -leigenSolver -lquadratureNode -lmomentSets -lmomentInversion -lfieldMomentInversion -lquadratureApproximation -lmomentAdvection -lPDFTransportModel -lmixing -lpopulationBalance"

# Set blastFoam OpenQBMM libraries
export BLAST_QBMM_LIBS="-L\$(BLAST_LIBBIN) -lblastQBMM $QBMM_LIBS"


# Set OpenQBMM include directories for use in Make files
export QBMM_INC="-I\$(QBMM_INST_DIR)/src/eigenSolver/lnInclude -I\$(QBMM_INST_DIR)/src/mappedList -I\$(QBMM_INST_DIR)/src/mappedPtrList -I\$(QBMM_INST_DIR)/src/Vandermonde/lnInclude -I\$(QBMM_INST_DIR)/src/quadratureMethods/momentSets/lnInclude -I\$(QBMM_INST_DIR)/src/quadratureMethods/momentInversion/lnInclude -I\$(QBMM_INST_DIR)/src/quadratureMethods/quadratureNode/lnInclude -I\$(QBMM_INST_DIR)/src/quadratureMethods/moments -I\$(QBMM_INST_DIR)/src/quadratureMethods/fieldMomentInversion/lnInclude -I\$(QBMM_INST_DIR)/src/quadratureMethods/quadratureApproximations/lnInclude -I\$(QBMM_INST_DIR)/src/quadratureMethods/momentAdvection/lnInclude -I\$(QBMM_INST_DIR)/src/quadratureMethods/PDFTransportModels/lnInclude -I\$(QBMM_INST_DIR)/src/quadratureMethods/populationBalanceModels/lnInclude -I\$(QBMM_INST_DIR)/src/quadratureMethods/mixingModels/lnInclude -I\$(QBMM_INST_DIR)/src/quadratureMethods/realizableOdeSolver"

# Set blastFoam OpenQBMM include path
export BLAST_QBMM_INC="-I\$(BLAST_DIR)/src/QBMM/lnInclude $QBMM_INC"

else
# Set libraries and include paths to null
export QBMM_LIBS=
export BLAST_QBMM_LIBS=
export QBMM_INC=
export BLAST_QBMM_INC=
fi

#------------------------------------------------------------------------------
