#----------------------------------*-sh-*--------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     | Website:  https://openfoam.org
#   \\  /    A nd           | Copyright (C) 2020 Synthetik Applied Technologies
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is derivative work of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# File
#     etc/bashrc
#
# Description
#     Startup file for blastFoam
#     Sourced from ~/.profile or ~/.bashrc
#     Should be usable by any POSIX-compliant shell (eg, ksh)
#
#------------------------------------------------------------------------------

export BLAST_PROJECT=blastfoam

################################################################################
# USER EDITABLE PART: Changes made here may be lost with the next upgrade
#
# BLAST_DIR is the location of the blastfoam installation which defaults to
# the directory containing this file if sourced by a bash shell.
#
# Please set to the appropriate path if the default is not correct.
#
export BLAST_DIR=$HOME/$WM_PROJECT/$BLAST_PROJECT

export BLAST_LIBBIN=$FOAM_USER_LIBBIN
export BLAST_APPBIN=$FOAM_USER_APPBIN
#export BLAST_LIBBIN=$FOAM_SITE_LIBBIN
#export BLAST_APPBIN=$FOAM_SITE_APPBIN

# Equation of state template directory
export EOS_DIR=$BLAST_DIR/etc/equationOfStateData
export ADDITIONAL_EOS=

# OpenQBMM install directory
export QBMM_INST_DIR=
# export QBMM_DIR=$HOME/$WM_PROJECT/OpenQBMM-dev
