#!/bin/bash
#
createDEps()
{
    echo "creating wall velocity plot"
    gnuplot<<EOF

    D(x)=abs(x/($3/$4));
    ms(t)=$4*t*1000;
    set terminal postscript eps enhanced color font 'Helvetica,40' linewidth 2\
        dl 8.0
    set output "blastFoam_wallD_validation.eps"
    set xlabel "Time [{/Symbol t} ms]"
    set ylabel "Normalized deflection [ {/Symbol d} / th ]"
    set grid
    set key right top box
    set size 2,2
    set autoscale
    set xrange [0:4]
#     set yrange [0:2.2]
    set mxtic 4
    set mytic 4
    plot'<sed -e "s/[(,)]//g" $1/D' using (ms(\$1)):(D(\$3)) title 'blastFoam' \
        with lines lt 1 linewidth 2 lc rgb 'black', \
         '$2/D.csv' using 1:2 title 'Neuberg et al'


EOF
}

# createDEps()
# {
#     echo "creating wall displacement plot"
#     gnuplot<<EOF
#
#     set terminal postscript eps enhanced color font 'Helvetica,40' linewidth 2\
#         dl 8.0
#     set output "blastFoam_wallD_validation.eps"
#     set xlabel "Time [ms]"
#     set ylabel "Displacement [mm]"
#     set grid
#     set key bottom right box
#     set size 2,2
#     set autoscale
#     set xrange [0:0.4]
#     set yrange [0:12]
#     set mxtics 4
#     plot '$2/exp_D.csv' using (\$1*1000):(\$2*1000) title 'Experiment' \
#         with points pt 7 ps 2 lc rgb 'red', \
#         '$2/sim_D.csv' using (\$1*1000):(\$2*1000) title 'Wardlaw et al' \
#         with points pt 5 ps 2 lc rgb 'blue', \
#         '<sed -e "s/[(,)]//g" $1/D' using (\$1*1000):(\$2*1000) title 'blastFoam' \
#         with lines lt 1 linewidth 2 lc rgb 'black', \
#
#
# EOF
# }

# test if gnuplot exists on the system
if ! which gnuplot > /dev/null 2>&1
then
    echo "gnuplot not found - skipping graph creation" >&2
    exit 1
fi

BLASTFOAM="../postProcessing/plateProbes/0"
VALIDATION="validationData"

th=$(foamDictionary ../properties -entry th0 -value)
S=$(foamDictionary ../properties -entry S -value)

echo $th $S
createDEps $BLASTFOAM $VALIDATION $th $S
# createDEps $BLASTFOAM $VALIDATION

echo Done
