#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# -- Create paraview file
paraFoam -builtin -touch

# - Create the mesh
runApplication blockMesh

# -- run the calc
runApplication $(getApplication)

# ----------------------------------------------------------------- end-of-file
