#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

paraFoam -builtin -touch

runApplication -s fluid blockMesh -region fluid
runApplication -s fluid decomposePar -region fluid
runParallel addEmptyPatch internalPatch internal -region fluid -overwrite
runParallel setRefinedFields -region fluid

runApplication -s solid blockMesh -region solid
runApplication -s solid decomposePar -region solid


runParallel $(getApplication)

# ----------------------------------------------------------------- end-of-file
