#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication -s fluid blockMesh -region fluid
runApplication -s walls blockMesh -region walls

runApplication decomposePar -allRegions

runParallel setRefinedFields -region fluid

runParallel $(getApplication)

# ----------------------------------------------------------------- end-of-file
