#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

runApplication splitMeshRegions -cellZones -overwrite

rm -rf constant/polyMesh

runApplication decomposePar -allRegions

runParallel setRefinedFields -region fluid

runParallel $(getApplication)

# ----------------------------------------------------------------- end-of-file
