#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

runApplication splitMeshRegions -cellZones -overwrite

foamDictionary constant/walls/polyMesh/boundary -entry entry0.walls_to_fluid.type -set mappedMovingWall
foamDictionary constant/fluid/polyMesh/boundary -entry entry0.fluid_to_walls.type -set mappedMovingWall

rm -rf constant/polyMesh

runApplication decomposePar -allRegions

runParallel setRefinedFields -region fluid

runParallel $(getApplication)

# ----------------------------------------------------------------- end-of-file
