#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

runApplication splitMeshRegions -cellZones -overwrite

rm -rf constant/polyMesh
foamDictionary constant/air/polyMesh/boundary -entry entry0.air_to_building.type -set 'mappedMovingWall'
foamDictionary constant/building/polyMesh/boundary -entry entry0.building_to_air.type -set 'mappedMovingWall'

runApplication decomposePar -allRegions

runParallel setRefinedFields -region air

runParallel $(getApplication)

# ----------------------------------------------------------------- end-of-file
