#!/bin/bash
createEps()
{

    case=$( cd .. && echo ${PWD##*/} )
    gnuplot<<EOF
    set terminal postscript eps enhanced color font 'Helvetica,40' linewidth 2\
        dl 8.0
    set output "explicitShallowWaterFoam_${case}_${1}.eps"
    set xlabel "X-Position (m)"
    set ylabel "${1} [${2}]"
    set grid
    set key right top
    set size 2,2
    set autoscale
    set xrange [0:1]
    set yrange [0:1.1]
    plot    "../$1" using 1:2 title 'Exact'\
                with points linewidth 8 linecolor rgb 'black',\
            "../$1" using 1:3 title 'blastFoam'\
                with lines lt 1 linewidth 2 linecolor rgb 'red'
EOF
}

# test if gnuplot exists on the system
if ! which gnuplot > /dev/null 2>&1
then
    echo "gnuplot not found - skipping graph creation" >&2
    exit 1
fi

# paths to data
createEps "h" "m"
createEps "u" "m/s"

echo Done
