#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
set -x

wclean libso phaseSystems
wclean libso interfacialModels
wclean libso phaseCompressibleTurbulenceModels
wclean libso kineticTheoryModels
wclean
