#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# -- Create paraview file
paraFoam -builtin -touch

# -- Create the mesh
runApplication blockMesh

# -- Decompose the mesh
runApplication decomposePar

# -- Run the calc
runParallel $(getApplication)

# -- Convert the lagrangian positions to view in paraview
runParallel -o convertLagrangianPositions

# ----------------------------------------------------------------- end-of-file
