#!/bin/bash
createEps()
{
    case=$( cd .. && echo ${PWD##*/} )
    gnuplot<<EOF
    set terminal postscript eps enhanced color font 'Helvetica,40' linewidth 2\
        dl 8.0
    set output "explicitShallowWaterFoam_${case}_${2}.eps"
    set xlabel "X-Position (m)"
    set ylabel "${2} [${3}]"
    set grid
    set key right top
    set size 2,2
    set autoscale
    set xrange [0:5000]
    plot    "$1" using 1:3 title 'blastFOAM' \
                with lines lt 1 linewidth 2 linecolor rgb 'red', \
            "validationData/$2.csv" using 1:2 title 'Exact' \
                with points linewidth 8 linecolor rgb 'black', \
            "$1" using 1:4 title 'topology' \
                with lines dt 1 linewidth 2 linecolor rgb 'orange', \

EOF
}

# test if gnuplot exists on the system
if ! which gnuplot > /dev/null 2>&1
then
    echo "gnuplot not found - skipping graph creation" >&2
    exit 1
fi

blastFoam_sample="../postProcessing/sampleDict/$(foamListTimes -case .. | tail -1)/Centerline_h_hTotal_h0.xy"

# paths to data
echo $blastFoam_sample
createEps $blastFoam_sample "h" "m"

echo Done
