#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
set -x

wclean libso finiteElements
wclean libso feMesh1
wclean libso pointPatchFields
wclean libso materialModels

wclean
