#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# -- Create paraview file
paraFoam -builtin -touch

# -- Create mesh
runApplication blockMesh

# -- Decompose the case
runApplication decomposePar

# -- Add internal patch
runParallel addInternalPatch

# -- Set initial conditions
runParallel setRefinedFields -updateAll
runParallel initializeLevelSet -updateAll

# -- run the calc
runParallel $(getApplication)

# -- Sample
runParallel -o foamPostProcess -func sampleDict -time 0.0001
runParallel -o foamPostProcess -func sampleDict -time 0.0002
runParallel -o foamPostProcess -func sampleDict -time 0.0003
runParallel -o foamPostProcess -func sampleDict -time 0.0004

# -- Create graphs
( cd validation && ./createGraphs )

# ----------------------------------------------------------------- end-of-file
