#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------
# set -x

wclean $targetType finiteVolume
wclean $targetType diameterModels
wclean $targetType thermodynamicModels
wclean $targetType radiationModels
wclean $targetType compressibleSystem
wclean $targetType dynamicMesh
wclean $targetType dynamicFvMesh
wclean $targetType errorEstimators
wclean $targetType functionObjects
wclean $targetType atmosphereModels
wclean $targetType solidModels

wclean $targetType QBMM
#------------------------------------------------------------------------------
