#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

wmake $targetType timeIntegrators
wmake $targetType diameterModels
wmake $targetType thermodynamicModels
wmake $targetType radiationModels
wmake $targetType finiteVolume
wmake $targetType fluxSchemes
wmake $targetType compressibleSystem
wmake $targetType dynamicMesh
wmake $targetType decompositionMethods
wmake $targetType errorEstimators
wmake $targetType dynamicFvMesh

wmake $targetType lagrangian/basic

wmake $targetType sampling

lagrangian/Allwmake $targetType $*

wmake $targetType functionObjects
wmake $targetType atmosphereModels

if [ ! -d "$QBMM_INST_DIR" ]
then
    echo "*******************************************"
    echo "    $QBMM_INST_DIR is not a valid directory"
    echo "    QBMM classes will not be compiled"
    echo "*******************************************"
elif [ -z "$QBMM_INST_DIR" ]
then
    echo "*******************************************"
    echo "No directory found for OpenQBMM"
    echo "QBMM classes will not be compiled"
    echo "Please add \"export QBMM_INST_DIR=QBMM_DIR\" to you .bashrc file"
    echo "*******************************************"
else
    wmake $targetType QBMM
fi
# -----------------------------------------------------------------------------

