#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication -s air blockMesh -region air
runApplication -s plate blockMesh -region plate

runApplication decomposePar -allRegions

runParallel setRefinedFields -region air

runParallel $(getApplication)

# ----------------------------------------------------------------- end-of-file
