#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# -- Create paraview file
paraFoam -builtin -touch

# -- Pre-process the stl
runApplication surfaceFeatures

# -- Create the mesh for the fluid
runApplication blockMesh

# -- Decompose the mesh
runApplication -o decomposePar -copyZero -force

# -- Cut out the stl
runParallel -o snappyHexMesh -overwrite

# -- Add internal patch
runParallel -o addEmptyPatch internalPatch internal -overwrite

sourceCase="../axisymmetricCharge"
sourceTime=$(foamListTimes -latestTime -case $sourceCase)

# -- Set the initial conditions for the fluid
#    rho is mapped for use with AMR
runParallel -o rotateFields $sourceCase \
    -sourceTime $sourceTime -additionalFields '(rho rhoU rhoE alphaRho.c4 alphaRho.air lambda.c4 impulse)' -uniform \
    -refine -extend

#- Run the calc
runParallel $(getApplication)

# ----------------------------------------------------------------- end-of-file
