#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# -- Create paraview file
paraFoam -builtin -touch

# -- Pre-process the stl
runApplication surfaceFeatures

# -- Create the mesh for the fluid
runApplication blockMesh

# -- Decompose the mesh
runApplication decomposePar -copyZero

# -- Cut out the stl
runParallel snappyHexMesh -overwrite

# -- Set the initial conditions for the fluid
for i in 1 2
do
    runParallel -s $i rotateFields ../axisymmetricCharge -sourceTime 1e-4 -additionalFields '(rho lambda.c4)'

    runParallel -s $i setRefinedFields -updateAll
done

runParallel rotateFields ../axisymmetricCharge -sourceTime 1e-4 -additionalFields '(rho lambda.c4)' -uniform

#- Run the calc
runParallel $(getApplication)

# ----------------------------------------------------------------- end-of-file
