#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

paraFoam -builtin -touch

# Create the mesh
runApplication blockMesh

# Decompose the case
runApplication decomposePar

# Run the solver
runParallel $(getApplication)
