#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

paraFoam -builtin -touch

# Create the mesh
runApplication blockMesh

# Run the solver
runApplication $(getApplication)
