#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# -- Create paraview file
paraFoam -builtin -touch

# -- Create the mesh for the fluid
runApplication -s fluid blockMesh -region fluid

# -- Create the mesh for the walls
runApplication -s walls blockMesh -region walls

# -- Decompose the meshes
runApplication decomposePar -allRegions

# -- Set the initial conditions for the fluid
runParallel setRefinedFields -region fluid

# ----------------------------------------------------------------- end-of-file
