#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

paraFoam -builtin -touch
runApplication blockMesh
runApplication $(getApplication)

( cd validation && ./createGraphs )